# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e8fa6dc147c61cee592608e06406370ef14b97cbddb2d2fc9024e47a3de2ab3913aea9f3e23ceb3a70fd132e991964fb4838f6f294b6a24c9e5825dc9d71e70a

test:
  secret_key_base: 8bc2d837caaed87369ff6b56fc565c1057f43539c88a1a1e5d703e40e9d62af81d0311e429831a2ff7c0aa968b3761924a42c12ed7643d1dd3eb82552512b228

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
